# *******************************************************************************
# Licensed Materials - Property of HCL
# (c) Copyright HCL Technologies Ltd. 2022. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# *******************************************************************************
apiVersion: v2
name: aida-ui
description: AIDA UI
type: application
version: 1.0.2
appVersion: "10.1.0.01"
